Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,14 +36,25 @@ jobs:
     - name: Install Rancher CLI
       run: |
           curl -LO https://github.com/rancher/cli/releases/download/v2.6.0/rancher-linux-amd64-v2.6.0.tar.gz
+              # Check if the file exists
+          if [ -f rancher-linux-amd64-v2.5.8.tar.gz ]; then
+            echo "Download successful"
+          else
+            echo "Download failed" && exit 1
+          fi
+      
+          # Extract the tarball (correct flag for .tar.gz files)
           tar -xzvf rancher-linux-amd64-v2.5.8.tar.gz
-    
+          
+          # List the files to check the extracted content
           ls -l
-    
- 
+          
+          # Move the Rancher binary to /usr/local/bin
           sudo mv rancher-linux-amd64-v2.5.8/rancher /usr/local/bin/rancher
-    
+          
+          # Verify the Rancher CLI installation
           rancher --version
+
 
       # Decode kubeconfig and set up kubectl
     - name: Set up Kubeconfig
